hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("waybar")
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("blueman-applet")
	hl.exec_cmd("dunst")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("sleep 2s && nextcloud --background")
	hl.exec_cmd("import-gsettings")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("gsettings set $gnome-schema icon-theme 'Colloid-Orange-Dracula-Dark'")
	hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 24")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("awww-daemon")
end)
