#!/bin/bash


xrandr --output DP-3-1-8 --scale 1.35x1.35
xrandr --output DP-3-8 --scale 1.35x1.35

mons -S 7,5:R --dpi 92

i3-msg restart

mons -S 7,5:R --dpi 92

sleep 1.0s

# Move these two workspaces to the second screen by default
i3-msg "workspace 1, move workspace to output DP-3-1-8"
i3-msg "workspace 2, move workspace to output DP-3-8"
i3-msg "workspace 6, move workspace to output DP-3-8"

i3-msg restart
