#!/bin/bash

echo "----------------------------"
echo "Update Nextcloud"
echo "----------------------------"

cd /data/containers/nextcloud

sudo docker compose pull
sudo docker compose build --pull
sudo docker compose up -d --force-recreate

echo "Waiting for containers to be online"
sleep 30s

sudo docker exec --user www-data nextcloud-app-1 /var/www/html/occ upgrade
sudo docker exec --user www-data nextcloud-app-1 /var/www/html/occ maintenance:repair --include-expensive
sudo docker exec --user www-data nextcloud-app-1 /var/www/html/occ db:add-missing-indices
sudo docker exec --user www-data nextcloud-app-1 /var/www/html/occ maintenance:mode --off
