#!/bin/bash

scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

echo "-------------------------------------------"
echo "Starting server update on $(date +'%D %T')"
echo "-------------------------------------------"

xbps-install -Syu

${scriptDir}/updateDockerContainersServer

reboot
