#!/bin/bash
. ~/.scripts/gitalias.sh

alias vim=nvim
alias c="xclip -selection clipboard"
alias ed=editdotfiles
alias dev=opendev
alias up=updateDotFiles
alias chromium=chromium --ozone-platform-hint=auto
alias signal-desktop="signal-desktop -ozone-platform=wayland"
# Reset smart card mapping for personal gpg key (if different yubikey is plugged in)
alias resetKey="remove-keygrips 0xB4B88025927E502D"
alias rk=resetKey
alias cat=colorize_cat
alias less=colorize_less

alias xi="xbps-install -Sy "
alias xr="xbps-remove "
alias xq="xbps-query "
alias xu="xbps-install -Syu"
alias w=weather

alias jp="jupyter notebook"

alias gpg=gpg2

alias mount_cvmfs="sudo mount -t cvmfs euclid.in2p3.fr /cvmfs/euclid.in2p3.fr && sudo mount -t cvmfs euclid-dev.in2p3.fr /cvmfs/euclid-dev.in2p3.fr"
alias mh="vim ~/Nextcloud/Documents/mh.md"

# Fix for kitty and ssh
alias ssh="kitty +kitten ssh"

# Fix PixInsight on wayland
alias PixInsight="env -u WAYLAND_DISPLAY PixInsight"

# Use wayland when available
alias chromium="chromium --ozone-platform-hint=auto"
alias signal-desktop="signal-desktop --ozone-platform-hint=auto"

# VPN connect to fhnw
alias vpn-fhnw="openconnect-sso --server vpn.fhnw.ch --user tino.heuberger@fhnw.ch"
