#!/bin/bash

if [[ $XDG_SESSION_TYPE == "wayland" ]]; then
	devFolder=$(find -L ~/dev -type d \( -exec /usr/bin/test -d "{}/.git" -a "{}" != "." \; -print -prune \
		-o -name .git -prune \) | wofi --dmenu --insensitive)
else
	devFolder=$(find -L ~/dev -type d \( -exec /usr/bin/test -d "{}/.git" -a "{}" != "." \; -print -prune \
		-o -name .git -prune \) | dmenu -i)
fi
kitten @ set-window-title "$EDITOR $(basename $devFolder)"
cd $devFolder
"${EDITOR:-vi}"
kitten @ set-window-title
