#!/bin/bash

UploadToProtonDrive(){
		# $1: Path to output tar.gz file
		# $2: Remote folder
		# $3: rclone remote name
		# $4: target recipient for GPG encryption
		#
		tarGzFile=$1
		echo "Encrypting archive ${tarGzFile}"
		gpg --output $tarGzFile.gpg --encrypt --recipient $4 --yes $tarGzFile
		echo "Uploading to File to ProtonDrive"
		rclone mkdir $3:$2
		rclone copy --protondrive-replace-existing-draft=true -P $tarGzFile.gpg $3:$2/
}

if [ -z "$(gpg --list-secret-keys)" ]; then
		echo "No GPG key for encryption currently available."
		echo "Generating one..."
		gpg --default-new-key-algo rsa8192 --gen-key
fi


read -s -p "Password for rclone configuration store: " rclone_password
echo
export RCLONE_CONFIG_PASS=$rclone_password

targetGPGKey="tinoheuberger@protonmail.com"

cd /data

UploadToProtonDrive tarBackups/Backup.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/Documents.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/Astrophotography.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/ConfigStoreAstroBot.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/containers.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/VirtualMachines.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
UploadToProtonDrive tarBackups/docker-data.tar.gz ServerBackups ProtonDriveBackup $targetGPGKey
