#!/bin/bash

CreateEncryptdTarBackup(){
		# $1: Path to output tar.gz file
		# $2: Path to folder to backup
		# $3: additional tar parameters
		eval tar -cv -I \"zstd -12 --long -T4\" $3 -pf $1 $2 
}

echo "---------------------------------------------------"
echo "--- Backing up files to compressed tar archives ---"
echo "---------------------------------------------------"

cd /data

mkdir -p tarBackups

CreateEncryptdTarBackup tarBackups/Backup.tar.gz Backup
CreateEncryptdTarBackup tarBackups/Documents.tar.gz Documents
CreateEncryptdTarBackup tarBackups/VirtualMachines.tar.gz VirtualMachines
CreateEncryptdTarBackup tarBackups/Astrophotography.tar.gz Astrophotography "--exclude 'Light' --exclude 'Lights' --exclude 'Night*' --exclude 'Flat*' --exclude '*DARKS*' --exclude 'Calib' --exclude '*Darks*' --exclude '*BIAS*' --exclude '*Bias*' --exclude 'gaia' --exclude '*.avi' --exclude '*.AVI'"
CreateEncryptdTarBackup tarBackups/ConfigStoreAstroBot.tar.gz ConfigStoreAstroBot
CreateEncryptdTarBackup tarBackups/containers.tar.gz containers
CreateEncryptdTarBackup tarBackups/docker-volumes.tar.gz docker-data/volumes
