#!/bin/bash

CreateEncryptdTarBackup(){
		# $1: Path to output tar.gz file
		# $2: Path to folder to backup
		# $3: target recipient for GPG encryption
		# $4: additional tar parameters
		tar -cv -I 'zstd -12 --long -T4' $4 -pf $1 $2 
}

echo "------------------------------------------------"
echo "--- Backing up files to proton drive archive ---"
echo "------------------------------------------------"

if [ -z "$(gpg --list-secret-keys)" ]; then
		echo "No GPG key for encryption currently available."
		echo "Generating one..."
		gpg --default-new-key-algo rsa8192 --gen-key
fi

cd /data

mkdir -p tarBackups

CreateEncryptdTarBackup tarBackups/Backup.tar.gz Backup $targetGPGKey
CreateEncryptdTarBackup tarBackups/Documents.tar.gz Documents $targetGPGKey
CreateEncryptdTarBackup tarBackups/Software.tar.gz Software $targetGPGKey
CreateEncryptdTarBackup tarBackups/Downloads.tar.gz Downloads $targetGPGKey
CreateEncryptdTarBackup tarBackups/VirtualMachines.tar.gz VirtualMachines $targetGPGKey
CreateEncryptdTarBackup tarBackups/Astrophotography.tar.gz Astrophotography $targetGPGKey "--exclude 'Light' --exclude 'Lights' --exclude 'Night*' --exclude 'Flat*' --exclude '*DARKS*' --exclude 'Calib' --exclude '*Darks*' --exclude '*BIAS*' --exclude '*Bias*' --exclude 'gaia' --exclude '*.avi' --exclude '*.AVI'"
CreateEncryptdTarBackup tarBackups/ConfigStoreAstroBot.tar.gz ConfigStoreAstroBot $targetGPGKey
CreateEncryptdTarBackup tarBackups/containers.tar.gz containers $targetGPGKey
CreateEncryptdTarBackup tarBackups/docker-data.tar.gz docker-data $targetGPGKey
