#!/bin/bash

sudo rsync -avhP --delete /data/Backup/ /backup/
sudo rsync -avhP --delete /data/Documents/ /backup/
sudo rsync -avhP --delete /data/Software/ /backup/
sudo rsync -avhP --delete /data/Downloads/ /backup/
sudo rsync -avhP --delete /data/VirtualMachines/ /backup/
sudo rsync -avhP --delete /data/Astrophotography /backup/
sudo rsync -avhP --delete /data/NextCloud /backup/
sudo rsync -avhP --delete /data/ConfigStore /backup/

echo "---------------------------------------"
echo "----------- Backup finished -----------"
echo "---------------------------------------"
