#!/bin/bash

echo "---------------------------------------"
echo "----------- Backup of files -----------"
echo "---------------------------------------"

rsync -avhP --delete /data/Backup/ /backup/Backup/
rsync -avhP --delete /data/Documents/ /backup/Documents/
rsync -avhP --delete /data/Software/ /backup/Software/
rsync -avhP --delete /data/Downloads/ /backup/Downloads/
rsync -avhP --delete /data/VirtualMachines/ /backup/VirtualMachines/
rsync -avhP --delete /data/Astrophotography /backup/Astrophotography/
rsync -avhP --delete /data/ConfigStoreAstroBot /backup/ConfigStore/ConfigStoreAstroBot
rsync -avhP --delete /data/containers /backup/containers/
rsync -avhP --delete /data/docker-data /backup/docker-data/

echo "---------------------------------------"
echo "----------- Backup finished -----------"
echo "---------------------------------------"
