#!/bin/sh

file_prefix=$1
remote_name="kDrive"
remote_folder="backup-rclone"
target_folder=$2

mkdir -p $target_folder

rclone lsf $remote_name:$remote_folder --include "$file_prefix*" | sort -d | while read file_name 
do
		rclone cat $remote_name:$remote_folder/$file_name
done | gpg -d | pv | tar -xJ --same-owner --directory $target_folder
