require("globalSettings")

require("config/lazy")
require("config/hop")
require("config/neotree")
require("config/colorscheme")
require("config/telescope")
require("config/lsp-zero")
require("config/treesitter")
require("config/noice")
require("config/lualine")
require("config/autocmd")
require("config/dressing")
require("config/comment")
require("config/debugging")
require("config/tabby")
require("config/autopairs")
require("config/neogit")
require("config/neotest")

require("config/lsp/jdtls")
require("config/lsp/texlive")
require("config/lsp/eslint")

require("after/plugin/keymap")
