require("globalSettings")

require("config/lazy")
require("config/hop")
require("config/neotree")
require("config/colorscheme")
require("config/telescope")
require("config/mason")
require("config/cmp")
require("config/treesitter")
require("config/noice")
require("config/lualine")
require("config/autocmd")
require("config/dressing")
require("config/comment")
require("config/debugging")
require("config/tabby")
require("config/autopairs")
require("config/neogit")
require("config/neotest")
require("config/gitsigns")

require("lsp.jdtls")
require("lsp.lua")
require("lsp.go")
require("lsp.ltex")
require("lsp.xml")
require("lsp.omnisharp")
require("lsp.python")
require("lsp.bash")
vim.lsp.enable({"jdtls", "lua", "go", "latex", "xml", "omnisharp", "pyright", "bashls"})

require("after/plugin/keymap")
