require("globalSettings")

require("config/lazy")
require("config/hop")
require("config/neotree")
require("config/colorscheme")
require("config/telescope")
require("config/lsp-zero")
require("config/treesitter")
require("config/noice")
require("config/lualine")
require("config/autocmd")
require("config/dressing")
require("config/lazygit")
require("config/jdtls")
require("config/texlive")
require("config/comment")
require("config/debugging")
require("config/tabby")
require("config/autopairs")

require("after/plugin/keymap")
