#!/bin/bash

# $1: Path to photo

fileNameWithoutExtension=$(basename "$1" | sed 's/\(.*\)\..*/\1/')
convert "$1" -quality 70 -resize 1080^x1920 -gravity center "${fileNameWithoutExtension}_thumb.webp"
vips dzsave "$1" tiled_photo --strip --suffix ".webp[Q=95,near_lossless=true]"
