#!/bin/bash

hugo || exit
server=lx42.hoststar.hosting
port=5544
# read -p "SFTP Server adress: " server
# read -p "SFTP Server port: " port
read -p "Username: " username

lftp -p ${port} -u ${username} sftp://<domain> -e 'set sftp:connect-program "ssh -a -x -oHostKeyAlgorithms=+ssh-dss -oStrictHostKeyChecking=no -oPasswordAuthentication=yes"' <<EOF
cd public_html
mirror -R public/ ./
EOF
