#!/bin/bash

hugo || exit
server=lx42.hoststar.hosting
port=5544
# read -p "SFTP Server adress: " server
# read -p "SFTP Server port: " port
read -p "Username: " username

sftp -P ${port} -oPort=${port} -oPasswordAuthentication=yes -o StrictHostKeyChecking=no -oHostKeyAlgorithms=+ssh-dss ${username}@lx42.hoststar.hosting:/public_html <<EOF
put -r ./public/*
EOF
