# ---------------------------------------------------
# HDR settings
# ---------------------------------------------------
tone-mapping=st2094-40
hdr-compute-peak=yes
gamma-factor=1.0
hdr-peak-percentile=99.8
hdr-peak-decay-rate=20
hdr-contrast-recovery=0.5
target-peak=100

# ---------------------------------------------------
# SDR to HDR
# ---------------------------------------------------
target-prim=bt.2020
target-trc=pq
inverse-tone-mapping=yes
tone-mapping=spline
target-colorspace-hint=auto
