[Tino-Proton]
source   = maildir://~/Mail/tino-proton
outgoing = smtp://tinoheuberger%40protonmail.com@127.0.0.1:1025
default  = Inbox
from     = Tino Heuberger <tinoheuberger@protonmail.com>
copy-to  = Sent

[Tino-SAG]
source   = maildir://~/Mail/tino-sag
outgoing = smtp://tino.heuberger%40sag-sas.ch@asmtp.mail.hostpoint.ch:465
default  = Inbox
from     = Tino Heuberger <tino.heuberger@sag-sas.ch>
copy-to  = Sent

[FAF-Proton]
source   = maildir://~/Mail/astrophotography-proton
outgoing = smtp://astrofotografie%40protonmail.com@127.0.0.1:1025
default  = Inbox
from     = Fachgruppe für Astrofotografie Schweiz <astrofotografie@protonmail.com>
copy-to  = Sent
