[Tino-Proton]
source   = notmuch://~/Mail
outgoing = smtp://tinoheuberger%40protonmail.com@127.0.0.1:1025
query-map = ~/.config/aerc/map-tino-proton.conf
notmuch-query = path:tino-proton/**
maildir-store = ~/Mail
default  = Inbox
from     = Tino Heuberger <tinoheuberger@protonmail.com>
outgoing-cred-cmd = bash ~/.config/mbsync/scripts/get-pw.sh tino-proton
copy-to  = Sent

[Tino-SAG]
source   = notmuch://~/Mail
outgoing = smtps://tino.heuberger%40sag-sas.ch@asmtp.mail.hostpoint.ch:465
query-map = ~/.config/aerc/map-tino-sag.conf
notmuch-query = path:tino-sag/**
maildir-store = ~/Mail
default  = Inbox
from     = Tino Heuberger <tino.heuberger@sag-sas.ch>
outgoing-cred-cmd = bash ~/.config/mbsync/scripts/get-pw.sh tino-sag
copy-to  = Sent

[FAF-Proton]
source   = notmuch://~/Mail
outgoing = smtp://astrofotografie%40protonmail.com@127.0.0.1:1025
query-map = ~/.config/aerc/map-astrophotography-proton.conf
maildir-store = ~/Mail
notmuch-query = path:astrophotography-proton/**
default  = Inbox
from     = Fachgruppe für Astrofotografie Schweiz <astrofotografie@protonmail.com>
outgoing-cred-cmd = bash ~/.config/mbsync/scripts/get-pw.sh astrophotography-proton
copy-to  = Sent
