Inbox=path:astrophotography-proton/** and tag:inbox and not tag:archived and not tag:deleted
Sent=path:astrophotography-proton/** and tag:sent
Archive=path:astrophotography-proton/** and tag:archived
Trash=path:astrophotography-proton/** and tag:deleted
