Inbox=path:tino-proton/** and tag:inbox and not tag:archived and not tag:deleted
Sent=path:tino-proton/** and tag:sent
Archive=path:tino-proton/** and tag:archived
Trash=path:tino-proton/** and tag:deleted
