vim.lsp.config('omnisharp', {
	cmd = { "omnisharp",
		'-z',
		'--hostPID',
		tostring(vim.fn.getpid()),
		'DotNet:enablePackageRestore=false',
		'--encoding',
		'utf-8',
		'--languageserver' },
	filetypes = { 'cs', 'vb' },
	root_markers = { '.git', '.sln', '.csproj', 'omnisharp.json', 'function.json' },
	settings = {
		RoslynExtensionsOptions = {
			LocationPaths = { "/home/cobra/.omnisharp/Rozlynator" },
			enableDecompilationSupport = true,
			enableImportCompletion = true,
			enableAnalyzersSupport = true,
			diagnosticWorkersThreadCount = 4,
			inlayHintsOptions = {
				enableForParameters = true,
				forLiteralParameters = true,
				forIndexerParameters = true,
				forObjectCreationParameters = true,
				forOtherParameters = true,
				suppressForParametersThatDifferOnlyBySuffix = true,
				suppressForParametersThatMatchMethodIntent = true,
				suppressForParametersThatMatchArgumentName = true,
				enableForTypes = true,
				forImplicitVariableTypes = true,
				forLambdaParameterTypes = true,
				forImplicitObjectCreation = true
			}
		},
		FormattingOptions = {
			EnableEditorConfigSupport = true,
			OrganizeImports = true,
			NewLine = "\n",
			UseTabs = false,
			TabSize = 4,
			IndentationSize = 4,
			SpacingAfterMethodDeclarationName = false,
			SpaceWithinMethodDeclarationParenthesis = false,
			SpaceBetweenEmptyMethodDeclarationParentheses = false,
			SpaceAfterMethodCallName = false,
			SpaceWithinMethodCallParentheses = false,
			SpaceBetweenEmptyMethodCallParentheses = false,
			SpaceAfterControlFlowStatementKeyword = true,
			SpaceWithinExpressionParentheses = false,
			SpaceWithinCastParentheses = false,
			SpaceWithinOtherParentheses = false,
			SpaceAfterCast = false,
			SpacesIgnoreAroundVariableDeclaration = false,
			SpaceBeforeOpenSquareBracket = false,
			SpaceBetweenEmptySquareBrackets = false,
			SpaceWithinSquareBrackets = false,
			SpaceAfterColonInBaseTypeDeclaration = true,
			SpaceAfterComma = true,
			SpaceAfterDot = false,
			SpaceAfterSemicolonsInForStatement = true,
			SpaceBeforeColonInBaseTypeDeclaration = true,
			SpaceBeforeComma = false,
			SpaceBeforeDot = false,
			SpaceBeforeSemicolonsInForStatement = false,
			SpacingAroundBinaryOperator = "single",
			IndentBraces = false,
			IndentBlock = true,
			IndentSwitchSection = true,
			IndentSwitchCaseSection = true,
			IndentSwitchCaseSectionWhenBlock = true,
			LabelPositioning = "oneLess",
			WrappingPreserveSingleLine = true,
			WrappingKeepStatementsOnSingleLine = true,
			NewLinesForBracesInTypes = true,
			NewLinesForBracesInMethods = true,
			NewLinesForBracesInProperties = true,
			NewLinesForBracesInAccessors = true,
			NewLinesForBracesInAnonymousMethods = true,
			NewLinesForBracesInControlBlocks = true,
			NewLinesForBracesInAnonymousTypes = true,
			NewLinesForBracesInObjectCollectionArrayInitializers = true,
			NewLinesForBracesInLambdaExpressionBody = true,
			NewLineForElse = true,
			NewLineForCatch = true,
			NewLineForFinally = true,
			NewLineForMembersInObjectInit = true,
			NewLineForMembersInAnonymousTypes = true,
			NewLineForClausesInQuery = true
		}
	}
})
